language: python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - travis_retry conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy
  - travis_retry pip install nose nose-cov coveralls setuptools
  - cd python/
  - travis_retry python setup.py install
script: nosetests --exe --with-xunit --xunit-file=nosetests.xml --with-coverage --cover-xml --cover-erase --cover-package=lopq --cover-xml-file=cobertura.xml test/tests.py
after_success:
  coveralls
after_failure:
  - echo "pip.log\n"; cat $HOME/.pip/pip.log
cache: apt