dist: trusty

language: java

jdk:
- oraclejdk8

dist: trusty

cache:
  directories:
  - $HOME/.m2

script: mvn install

after_success:
- travis/deploy.sh

branches:
  only:
  - master
  - /^v.*$/
  - jdk10

env:
  global:
  - secure: cSG9KE131wt+NfNU0rHnX4eSdZ9T6bYcdB6oYCLgGUoTDgMM7xf8e1Fg5o8w2egkS2Ch9huC0VPn3GpBJC8GGq9t+ct2Ay2hKfGb1+pktFANAwNg7d3FnvTYgyLmwvayWzenl+9DP+VT3kyiaks5nbPfzozUzQG1KYVAKHqT3j1jvGyuFwBO8fBbydHTmou9OtxWfw48AQmxtvkmr/z+pXoBzvstOYl5sCuU6QgLv0jEW22IoocELqOCMOQQNc770loxr61wmKi2YnfNxw4Bj3IQU61TzSQeBOMPQa442pcg9r6UO4BcTzCkj3GN61zI7qznHmd6FjMTGSHPvRPFuRibmSWSvYsSoghDJUO8HjeeRcJb5L3yepVF33kyyYyr8pxMuPG8dkhdWEmYX21dOCYbOvQHK0HRaeXHheMlnTOtuQqPfCgUIqdbO2tths8Yoyioa9RCdgV9leIhb06ha7YznYwFwNDKXNDgXqRG5jM3JETP1YIVvpHC8GL2A65JlPrtEHorV9jOi+e7+QXngtAR5uwPOkHLvMjSATfv+MsvqoPDqJOMo2IBjcVf83pVOWGj+6EglnhLoHgOVmHADZdpOm7kbNomfexwZR9qrYmWvWomWp5zf26jIzr/SRUAkUOWKLB0uMACdhYFsZ6NA+7SPK4F+ZSacmovTFNjRa0=
  - secure: ZoYzK1sZ/GU/sO+VjFae/VnTayTMv9BWNbwn5jSl01w0UTHeL9MyaZpyTEKu7FrVgKZ9eKoVFvkPNCEfIh8gOZcpLa+P9Okdb35ZQcTrYwJsD5c+vccugNQEWCiVErNjgzMdby2CxUZ/LRPiT+GxxPCCuMsUpJz6rtif/tqRoiLdOYbvv4gRQRwNj06mtdPPTUhYqv8FofiydTHinOenHZKLcAcDZSMe4gcl7pcAQFS8znUFv4IW04QcrNulgXgYXYg8egojiEqBmS4gECmR8sPpowQNuULydzZOyHf/OHY5qjUIYnobZw9lhG1uoS5GCmUI3TZeQyI2vwKd/eMDQOVb4PVdhkdcQHl7J56OyBS8TXS17azSuIhIuno6v3I4Cjf5Qkus5g9vfzNe8hG+NhCPBKvJJS327DVlSg2dJzy61a0+lUt6WpiTIXECKuyiUlWYcpBzl8UW1vM0jybQNmNixCmqiWVA038rSN2gxTb5CZgAlMnPCXZMxXujZERjNPY58dLtgtBsJ2ByhmBweFGHMehX/ivFkTHbd/VqjrJDubwKL4N/75MpBHypoOlvuhWMafRMEFBKY033uSiYQqyG72L1xGLFrL2nWZaSa0sgMbhrrvaTC4KkkGVhjcmTjpzFDxEWkRcu3UU5OOxQs1KqTATQo9ql+okKWrTozd4=
