language: node_js

node_js:
  - "8.4.0"
branches:
  except:
    - gh-pages

script:
  - npm test

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5ba2780eb32dc366def2
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
