env:
  matrix:
    - WITH_CUDA=false WITH_CMAKE=false WITH_IO=true
    - WITH_CUDA=true WITH_CMAKE=false WITH_IO=true

sudo: required

language: scala
scala:
   - 2.10.4

git:
    submodules: false

compiler:
  - gcc

jdk:
  - oraclejdk7

# Cache Ubuntu apt packages.
cache:
  apt: true
  directories:
  - /home/travis/miniconda

before_install:
  - export NUM_THREADS=4
  - export SCRIPTS=./scripts/travis
  - export CONDA_DIR="/home/travis/miniconda"
  - git submodule update --init --recursive

install:
  - sudo -E $SCRIPTS/travis_install.sh

before_script:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib:/usr/local/cuda/lib64:$CONDA_DIR/lib
  - export SPARK_HOME=/home/travis/build/yahoo/CaffeOnSpark/spark-1.6.0-bin-hadoop2.6/
  - export PATH=$CONDA_DIR/bin:$PATH
  - if ! $WITH_CMAKE; then $SCRIPTS/travis_setup_makefile_config.sh; fi

script: $SCRIPTS/travis_build_and_test.sh

notifications:
# Emails are sent to the committer's git-configured email address by default,
# but only if they have access to the repository.  To enable Travis on your
# public fork of Caffe, just go to travis-ci.org and flip the switch on for
# your Caffe fork.  To configure your git email address, use:
#     git config --global user.email me@example.com
  email:
    on_success: always
    on_failure: always

# IRC notifications disabled by default.
# Uncomment next 5 lines to send notifications to chat.freenode.net#caffe
#   irc:
#     channels:
#       - "chat.freenode.net#caffe"
#     template:
#       - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
