language: go
env:
  global:
    secure: "NsbPsieJoBXvzLwx6XYffg4/80nRqhV5dHZUP8mRTMkmndfuR+r5iY4Os7QYxzYC88i4bx8rh0yOIOtfzGuLnvnuQRMAGXBLekpw/r2kYX9Tgn879DGxu9IG1b0Z1wJmUu4tflNLNSfjn0pxYsI+jWpmHuRTpNeyCit92iSvvMDOKvJsvMncMFEy/sLDVZ1ij7w48RhSLO9IvA4SVUYt9D42VaHcJ05IGdGlFvuoJQWJvckAqVqTMNnLil6QVBZ5AgrcC8BCaafGFkFK/uqgZPRNIbFFcFXFtOBYGLV6H31HJGo9eD17E2QtUtQvBHBi8MmI8cvV9QdpL2WzviZuxBrJEH6Dob4xZNEH44rFP1wfGT97kaBAOLhPoO9TU5AfzTaVg5vvhcTSw9cbcb9jqli7j8sfUPVW8c6yk5loYa4YbKGVKmlwLPCgeT+3pqTo78Uaz1mqg83gg3UZkzou0UMHfN8K87AWrcqB8jeLp2gSk3NwGLVPmLaklQPlY746XKvz4zH0exuCpyUGG3Bq6Fo2Cb9Wg0WZwoNDP6Hw8epvsIcItN8kIFTgiHbq2RBzCWNBS2ZgsAYX+oFAwiAwBzN5nTqmaVv/M6lAfQpMkJtQLZ2G+D1vENiPOxI/U8s8lmQj/6zoQoB6mZbLTN92tJv5wi0PS25mHKW8JCvrY8Q="

install:
  - GOOS=darwin GOARCH=amd64 go get -x -t -v ./...
  - GOOS=linux GOARCH=amd64 go get -x -t -v ./...

before_deploy:
  - for i in $GOPATH/bin/rdl-gen-parsec* ;do cp $i $i-linux;done
  - for i in $GOPATH/bin/darwin_amd64/rdl-gen-parsec*;do cp $i $GOPATH/bin/`basename $i`-darwin;done
  - zip -j rdl-gen.zip $GOPATH/bin/rdl-gen-parsec*-{darwin,linux}
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag v0.1.$TRAVIS_BUILD_NUMBER -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUBKEY@github.com/yahoo/parsec-rdl-gen --tags

deploy:
  provider: releases
  api_key:
    secure: guVyQQaaXhvp7dXaft2Xvvb8GD3P4FKVJOr+m+4u4yDPDR7GOO4FKJsMHJZOBltoSjSfOrnZhVR+7/WfmzUEcrwZUT4FkGdqX/nlNYlanq0zWND4+teDNG5ZKp9734VGMvQVZGqEAmSgntMNuGgEVKg34JSmvpOT7vMIB+jDmTM2uHwqUO1Rb5zExg7zcC9nozuwATcb36FmFwevU9c3hkuOMSudru/Pfd52fNX3Mro6U5heZ1X6m/K1jJ+qwLdsgjoaPwzOxJH+zud4GMT0qCv4rF6VV5mFBd34bITvBOKezvyNDaP4M6bgq5IKCAvpCGh/tZ5kKpnX8ok3nnmt7R5HLyeDKTlKtL/93enLwB52Kj69hH9OLjnZBFaTkKhchYIFYM8Vi81Qroc3AkpijNoeyVHi29UiHJBkCkNwkQjbCr1nk0xczlPgE4VEw4myDY1yJbKTT8Hsh4ksgqg0kaEYL2LnMKbsXrBjzgbJJKCu2DIfJm0+CPuLBa/+svXacfkdaG4QF2SxLQfd5QbGbTIScDj2qbIOOelxG9CDShHAZqOfRYyX4mRP57wh8J2aSqX1bsiTBtVDgjSQiQn0PWYBSj1c/eV6IVHxa+EJJfN2BJ2WaFxMsKpVoxz6rPByb/8E/T8zLdM/6/8ygtq/R+Xr9X2nP8QGSlcnmEWRwVU=
  skip_cleanup: true
  file: rdl-gen.zip
  on:
    repo: yahoo/parsec-rdl-gen
    tags: false

branches:
  only:
    - master
